# Entry point for GitLab CI for the AppointDent Project

image: node:docker
services:
  - docker:dind

variables:
  SERVER_PATH: server
  CLIENT_PATH: client
  APPOINTMENT_SERVICE_PATH: services/appointment-service
  DENTIST_SERVICE_PATH: services/dentist-service
  NOTIFICATION_SERVICE_PATH: services/notification-service
  PATIENT_SERVICE_PATH: services/patient-service
  SESSION_SERVICE_PATH: services/session-service
  # add any additional paths

# We permit four stages: (i) install, (ii) lint, (iii) test (iv) test.
stages:
  - install
  - lint
  - test
  - build

before_script:
  - apk update && apk add --no-cache bash 

# TODO: fix caching of dependencies to ensure faster
# pipeline performance.

install-client:
  stage: install
  image: node:alpine
  tags:
    - docker
  needs: []
  cache:
    key:
      files: 
        - $CLIENT_PATH/package-lock.json
    paths:
      - $CLIENT_PATH/.npm
  before_script:
    - cd $CLIENT_PATH
  script:
    - echo "Installing dependencies for client..."
    - npm ci --cache .npm --prefer-offline
    - echo "Dependencies for client have been installed!"
    # add a proper check that `.npm` is installed

install-server:
  stage: install
  image: node:alpine
  tags:
    - docker
  needs: []
  # Cache dependencies using the `package-lock.json` file.
  cache:
    key:
      files:
        - $SERVER_PATH/package-lock.json 
    paths:
      - $SERVER_PATH/.npm 
  before_script:
  - cd $SERVER_PATH
  script:
    - echo "Installing dependencies for server..."
    - npm ci --cache .npm --prefer-offline
    - echo "Dependencies for server have been installed!"
    # add a proper check that `.npm` is installed

# Currently disabled because client does not support `npm run lint`.
# lint-client:
#   stage: lint
#   image: node:alpine
#   tags:
#     - docker
#   needs: ["install-client"]
#   before_script:
#     - cd $CLIENT_PATH
#   script:
#     - echo "Linting client..."
#     - npm run lint
#     - echo "Lint successful!"
#   allow_failure: true

lint-server:
  stage: lint
  image: node:alpine
  tags:
    - docker
  needs: ["install-server"]
  before_script:
    - cd $SERVER_PATH
  script:
    - echo "Linting server..."
    - npm run lint
    - echo "Lint successful!"
  allow_failure: true

# TODO: add testing stage for server (via Postman)

# TODO: finish the building stage

build-client:
  stage: build
  image: node:alpine
  tags:
    - docker
  needs: ["install-client"]
  before_script:
    - cd $CLIENT_PATH
  script:
    - echo "Building the client..."
    - npm run build
    - echo "Build successful!"
  artifacts:
    paths:
      - $CLIENT_PATH/dist
  only:
    - main # we don't want to excessively exhaust the servers